version: "3"
services:
  db:
    env_file:
      - .env
    image: "postgres"
    container_name: "prez_pg_db"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "127.0.0.1:2345:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  default:
    external:
      name: incubator-superset_default
